# Generated by Django 5.2.8 on 2025-11-21 05:06

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='contact_icon',
            new_name='contact_firstname',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='contact_title',
            new_name='contact_lastname',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='contact_description',
            new_name='contact_message',
        ),
        migrations.AddField(
            model_name='contacts',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='contact_mobilenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
