# Generated by Django 5.2.8 on 2025-11-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_courses_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='courses_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='courses/'),
        ),
    ]
